### ISSUE TITLE
Height adjustment

### ISSUE THREAD

**Issue by L0kidor** [ma-5/ma5slider#1]
Hi, 
Currently the height is fixed by the first image that is displayed, unless you resize your browser.
Is it possible to adjust the height of the slider to fit image's height in a responsive way ?

**Comment by ma-5** [comment]
Hi, Height area is set by `<canvas class="canvas">`. You can use method "updateCanvas" and event "animationEnd" for example in `<head>`:

```
<script>
    $(window).on('load', function () {
        $('.ma5slider').on('ma5.animationEnd', function () {
            $(this).ma5slider('updateCanvas');
        });
    });
</script>
```

**Comment by L0kidor** [comment]
Great ! Thank you. 
This function wasn't referenced in the documention, I could have search in the code.
Mea culpa and thank you again.
